### ISSUE TITLE
Make Query<T>(string query, Dictionary<string, object> parameters) public

### ISSUE THREAD

**Issue by irriss** [bordereast/arangodb-net-core#2]
Hi there,

Please mark method as public
`Query<T>(string query, Dictionary<string, object> parameters)` 
of ArangoDatabase 

It is very useful if the number of parameters is unknown before runtime.

**Comment by agrothe** [comment]
Would this method not suffice?

`public ArangoQuery<T> Query<T>(string query, dynamic parameters)`

**Comment by irriss** [comment]
Not possible to use it if you don't know list of parameters in advance.

Regards,
Ruslan

On 3 Aug 2017 8:11 pm, "Andrew Grothe" <notifications@github.com> wrote:

Would this method not suffice?

public ArangoQuery<T> Query<T>(string query, dynamic parameters)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bordereast/arangodb-net-core/issues/2#issuecomment-319951217>,
or mute the thread

**Comment by agrothe** [comment]
You can cast a [Dictionary into a dynamicobject](https://stackoverflow.com/a/18293398/153083), but I can also add an method overload to accept a dictionary as well.

**Comment by irriss** [comment]
Please add. Because dynamic made of dictionary is not recognised via
reflection which you use to get dictionary in that method.

I tried all this. Nothing works.

Regards,
Ruslan

On 3 Aug 2017 9:37 pm, "Andrew Grothe" <notifications@github.com> wrote:

You can cast a Dictionary into a dynamicobject
<https://stackoverflow.com/a/18293398/153083>, but I can also add an method
overload to accept a dictionary as well.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bordereast/arangodb-net-core/issues/2#issuecomment-319970989>,
or mute the thread

**Comment by agrothe** [comment]
Released via nuget: [https://www.nuget.org/packages/BorderEast.ArangoDB.Client/0.1.8](https://www.nuget.org/packages/BorderEast.ArangoDB.Client/0.1.8)

**Comment by irriss** [comment]
Thanks for resolving it so quickly. Is there a particular reason to compile as AMD64?

_MSB3270 There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "..\.nuget\packages\bordereast.arangodb.client\0.1.8\lib\netcoreapp1.1\BorderEast.ArangoDB.Client.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture ..._

**Comment by agrothe** [comment]
Interesting, I don't recall changing the architecture. I'll have a look.

**Comment by agrothe** [comment]
The configuration is set to "Any CPU".  You can try building the project on your machine and see if that makes a difference.
