### ISSUE TITLE
Bind Parameters change case silently

### ISSUE THREAD

**Issue by irriss** [bordereast/arangodb-net-core#7]
Parameter names silently converted to camelCase which causes run time errors

Consider following code
```
            var queryString = @"
                UPSERT { _key: @_key} 
                INSERT { Subscriptions: @Subscriptions, _key: @_key} 
                UPDATE { Subscriptions: @Subscriptions, _key: @_key} 
                IN Collection RETURN NEW._key";
            var document = new Dictionary<string, object>
            {
                { "_key", "123" },
                {"Subscriptions", "AAAA" }
            };
            var q = db.Query<string>(queryString, document);

            var r = q.ToListAsync().Result;

```

Parameter "Subscriptions" starts with capital consistently in query and in parameters dictionary. However, during execution this code will fail because bind parameters will be changed to have small first letter due to CamelCaseNamingStrategy in ArangoDBContractResolver

The error message will be "AQL: no value specified for declared bind parameter 'Subscriptions' (while parsing)"

@agrothe could you review why CamelCaseNamingStrategy  is used? Attempt to change it to Default one causes tests to fail.

**Comment by agrothe** [comment]
I believe the CamelCaseNamingStrategy is used as well formed JSON is considered to be camel case, but that's about it. I'll have to dig a bit deeper.

If the tests are written to expect camel case, but camel case isn't required, they can be rewritten.

**Comment by agrothe** [comment]
@irriss There is one specific test case for the camel casing. Does the `DefaultNamingStrategy` work otherwise for you? If so, we can create an overload on `ArangoDBContractResolver` to pass in a `NamingStrategy`. 

I'm trying to recall if there was a specific reason, but I think it's only my preference and nothing else. If the foreign keys work with the `DefaultNamingStrategy` I certainly have no issue with it, as long as I can pass in a `CamelCaseNamingStrategy` for myself.

**Comment by agrothe** [comment]
@irriss try installing pre-release 0.1.10-rc. Just curious if it works with your setup. Default naming strategy is now `DefaultNamingStrategy` and `ArangoDBContractResolver` has an available overload to use other naming strategies.

PS: also added CreateDatabase method.

**Comment by irriss** [comment]
@agrothe I have tried new version. For my specific case it works fine, however, I found that BorderEast.ASPNetCore.Identity.ArangoDB now cannot insert a new user. It fails with strange http error StatusCode: 409, ReasonPhrase: 'Conflict'

If I change default Contract Resolver back to Camel Case it works fine.

I could not find a nice way to override Contract Resolver to Camel Case inside Identity lib. Could you have a look at that?
